### ISSUE TITLE
Redesign Trophy Room (Aka achievements page)

### ISSUE THREAD

**Issue by chenga3** [codersforcauses/foodbank#174]
## Part 1 - Frontend
- [x] #200
- [x] Create 'TrophyGroup' component with trophy display 
- [x] Add progress bar to 'TrophyGroup' component
- [ ] ~~Create JS objects to represent prototype trophies~~
- [ ] ~~Update trophy page and 'TrophyGroup' component to render prototype trophies~~

## Part 2 - Backend
- [ ] Add user's numTrophies to Firebase
- [ ] Frontend makes API calls to load numTrophies to Firebase

## Part 3 - Game Logic
- [ ] Decide unlock conditions for all trophies
- [ ] Implement logic for updating backend upon simple unlock condition (eg. Signing up)
- [ ] Implement logic for updating backend for all trophies

design should resemble 
![image](https://user-images.githubusercontent.com/22740095/143578365-fb64466e-03cb-4c1a-bbfc-d2e8a6bc9e16.png)
