### ISSUE TITLE
Intergrate Authentication Page With Firebase 

### ISSUE THREAD

**Issue by DBprassan12** [codersforcauses/foodbank#175]
This task will see the Implementation of user authentication with Firebase.

Food bank's login prompt page has already been created.
The login Page utilizes a name and birth date to load the user's progress

Part 1 
-----------------------------------------------------------------------------------------------------------------
- [x] set up Firebase and document configuration (almost done)
- [x] The username String needs to be converted into an email for processing
- [x] The birth date String needs to be converted into a password for processing

Examples 
===============
Username: Bob123
Password:
![image](https://user-images.githubusercontent.com/22740095/144623096-8b18d4d5-3857-4056-8399-d409fd21acf6.png)

-----------------------------------------------------------------------------------------------------------------
User registration needs to be integrated with Firebase

- [x] The email field needs to be integrated with Firebase.
- [x] The Password field needs to be integrated with Firebase.
- [x] Test integrations

Part 3 
-----------------------------------------------------------------------------------------------------------------
- [ ] integrated User's progress with Firebase ( sub task of issue  Create user save system #27)
https://github.com/codersforcauses/foodbank/issues/27
