### ISSUE TITLE
Notion - Content Management System

### ISSUE THREAD

**Issue by DBprassan12** [codersforcauses/foodbank#190]
## Notion will be used as a Content Management System.

We will store images and associated information of **everyday food** characters, **superhero food** characters and recipes in a Notion workspace, from which the client will be able to add, edit or delete food characters or recipes.

### Notion workspace requirements:
* There should be a table for managing the everyday food characters. The following data should be stored with every **everyday food character** record:
  * What location in Tucker Island the character is associated with
  * The "About", "Likes..." and "Recipe" information
  * The associated **superhero food character** with its image
    * The "Superpowers", "Use" and "Likes..." information of that **superhero food character**
* There should be a table for managing recipes. The following data should be associated with every recipe:
  * Ingredients
  * Equipment
  * The recipe steps with associated images.

**Note:** Please refer to the **Superhero Foods Handbook** and **Let's Cook** handbook respectively for best understanding these requirements as the information on certain pages of this book reflect the information that needs to be shown to the user in the app.

### Part 1
  
- [x]    Setup notion workspace for Foodbank  
- [x]    Setup notion API (Create an integration - Use internal integration for now)  
- [x]    Share a database with your integration  

### Part 2
- [x]    Create two tables - one for food characters and one for recipes
- [x]    Populate the Notion tables with some characters and recipes respectively (Add some item to the database)  (We still need to confirm if all assets are up to date with their current branding.)
  * You could just do either one for now - characters or recipes, to start off with and and continue with the rest of the steps to see that the integration stuff works or not.
- [x]    Add the required fields for every record in each of the tables.

### Part 3 (Integration)

- [ ]   Integrate the characters table with the characters page of the locations in the tucker island (homepage) (Depending on issue #26. Will be integrated once it's done)
- [x]  Integrate the recipes table with the recipes page.
- [x]   Integrate the recipe page
- [ ]   Integrate the View All steps page
- [ ]   Integrate the Let's Cook page
- [ ]   Test if all assets are being scaled and pulled accordingly

For more information, please reference https://developers.notion.com/docs
This video has a very helpful demonstration on how to fetch data from a notion database using NextJS:
https://www.youtube.com/watch?v=YMbQxavquKc

The following video may be useful for setting up notion API: https://www.youtube.com/watch?v=zVfVLBjQuSA
