### ISSUE TITLE
Create Tucker Island page

### ISSUE THREAD

**Issue by thaingu** [codersforcauses/foodbank#24]
![Map small](https://user-images.githubusercontent.com/38243574/101128754-3e3baa00-363b-11eb-9d8b-9d518946abfb.jpeg)

Requirements:

- Create page that features Tucker Island from: https://www.thelitcentre.org.au/media/1672/foodbank-wa-handbook-online-2020.pdf
- Each zone is clickable with either a description appearing after clicking or navigating to a detailed location view.
- Animations and SFX are also something to consider.
- Essentially an nav map similar to neopets/club penguin.

Tasks to complete:
- [x] #41: Add tucker island map to homepage
- [x] #42: Add clickable towns to map
- [x] Create popup text boxes to describe location
- [ ] Add mobile view with map broken into two switchable parts
- [ ] Add hover effects and click animations
