### ISSUE TITLE
Create user save system

### ISSUE THREAD

**Issue by thaingu** [codersforcauses/foodbank#27]
The app includes several unlockable features like character transformations, Food groups and badges/achievements. Users should be able to save their progress across sessions. Since the target audience is children we are considering a simple username authentication system without a password as this will assist in keeping work for teachers down and will remove the need for an email reset system. An alternative to a password could be a birth date or birth year which will help decrease brute forcing attempts slightly. The data for each user is extremely trivial and we will not be storing any personal info and the only thing an intruder would be able to do is unlock more content so we feel this weak authentication system does not pose a risk.

Tasks to be completed:
- [x] Create database schema and connect database to backend
- [ ] Create api endpoint for new user signup
- [ ] Create api endpoint for returning user log in
- [ ] Create api endpoint to get and update user data

**Comment by eddie-atkinson** [comment]
Create a unique QR code on sign-up and scan it from the app to sign in? Magic links emailed?

**Comment by Drewbi** [comment]
They were kind of tipping between wanting to restrict access to only schools that had signed up for it and allowing access to everyone but I think we decided on allow access for everyone so students could use it at home as well as streamlining the setup process for schools.

Basically once you have the url to the app you can "Sign-up" with just a basic username and no password so kids don't forget it and lose their progress. If they lose their username thats kinda on them. We could also restrict access by making them enter their birthday as a type of verification which would help limit kids brute forcing other peoples saves.
