### ISSUE TITLE
Create Town/Area Pages

### ISSUE THREAD

**Issue by Drewbi** [codersforcauses/foodbank#36]
### Create a page template to render characters associated with the respective locations

Make the template for these pages. (These characters and their associated information will be fetched from a Notion CMS, in the backend.)

**Exception :** Healthy town will actually redirect to the drag and drop game.

Tasks to complete:
- [ ] Design the page (Something similar to image 1)
- [ ] Create Everyday Food Character page (Similar to image 2)
- [ ] Create Transformed (Superhero Food) Character page (Similar to image 3)

Image 1: 
![image](https://user-images.githubusercontent.com/22740095/143591853-97d8e610-a552-47f2-901c-bd06e60001db.png)

Image 2:
![image](https://user-images.githubusercontent.com/22740095/143592938-73b7e6df-5acf-44d7-bffb-1e9955495228.png)

Image 3:
![image](https://user-images.githubusercontent.com/22740095/143593977-2310728a-7688-4b87-834f-20fe8e590425.png)

Background images:
https://www.mediafire.com/file/bo7a5e0lmpqybek/Background_Assets.zip/file
