### ISSUE TITLE
Create textfield component

### ISSUE THREAD

**Issue by JeremiahPinto** [codersforcauses/foodbank#52]
Create Textfield component with styles as shown:
![Screen Shot 2020-12-08 at 4 47 56 pm](https://user-images.githubusercontent.com/24516879/101461077-5e3dd700-3975-11eb-84a5-10dff2c88f54.png)

Will use font `Bliss` 

### Tasks:
- [x] Input should have label
- [x] Input should have varying types: `text`, `password`, `tel` etc.
- [x] Should be keyboard acessible
- [x] Should have description if props sent
- [x] Should have error handling and show sensible errors to users

**Comment by Drewbi** [comment]
Last pass icon on right is not part of design**
