### ISSUE TITLE
Create Banana guy introduction

### ISSUE THREAD

**Issue by Drewbi** [codersforcauses/foodbank#56]
## Task

As soon as the user loads tucker island for the first time mr banana man shows up to give a brief intro to the island. We just want him to say something about clicking on the locations and discovering foods because anything more complex will be hard for children to understand.

<img width="444" alt="Screen Shot 2020-12-08 at 6 52 15 pm" src="https://user-images.githubusercontent.com/38243574/101474760-8255e400-3986-11eb-818d-71b2089daf0a.png">

This kind of content but as a dialog such as this:
![82ec9eed15c4050b45d25ba21c8eea48cf15dc57](https://user-images.githubusercontent.com/38243574/101475048-d365d800-3986-11eb-8845-37560b062719.png)

Requirements:
- [ ] Show picture of banana man
- [ ] Show box with text in it
- [ ] Progress through on click
- [ ] Animate dialog open

Epic: #22
